name: Manual run & Integrated when push on main

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Instalando dependências da pasta backend
        working-directory: ./backend
        run: npm install

      - name: Instalando dependências da pasta tests
        working-directory: ./tests
        run: npm install

      - name: Iniciando backend em segundo plano
        working-directory: ./backend
        run: |
          nohup node app.js & sleep 5

      - name: Executar Testes de API
        working-directory: ./tests
        run: npm test

      - uses: actions/upload-artifact@v3
        with:
          name: relatorio-de-testes
          path: ./tests/jest-stare